# Core GCP Settings
spring.cloud.gcp.project-id=cybernetic-pact-417810

# Cloud SQL Configuration
spring.cloud.gcp.sql.instance-connection-name=cybernetic-pact-417810:asia-south2:prabhu-pgdemo2-dev
spring.cloud.gcp.sql.database-name=wallet-app

# Database Credentials
#datasource.username=postgres <--default admin access
spring.datasource.username=prabhu-demo-db-devuser
spring.datasource.password=~Z/-}H;Fzcn$95Xr

#supabase postgreSQL properties
#spring.datasource.url=jdbc:postgresql://db.bvxnaiullpinsiqnftbf.supabase.co:5432/postgres?user=postgres&password=jwn05tOjgIZU5z43
#spring.datasource.username=postgres
#spring.datasource.password=K*t2_cxeQeskHP%40
#spring.datasource.driver-class-name=org.postgresql.Driver
# Sets the PostgreSQL dialect for Hibernate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# hibernate setup
#Testing
spring.jpa.hibernate.ddl-auto = create-drop

## --- Stage 1: Build the application ---
#FROM maven:3.9.6-eclipse-temurin-17 AS build
#WORKDIR /app
## Copy the pom.xml and source code
#COPY pom.xml .
#COPY src ./src
## Build the application and skip tests for speed
#RUN mvn clean package -DskipTests
## --- Stage 2: Run the application ---
#FROM eclipse-temurin:17-jre-alpine
#WORKDIR /app
## Copy the built JAR from the first stage
#COPY --from=build /app/target/*.jar app.jar
## Expose the default Spring Boot port
#EXPOSE 8090
## Execute the application
#ENTRYPOINT ["java", "-jar", "app.jar"]
#
